### ISSUE TITLE
Tracker crashes when loading a seed file with weighted settings

### ISSUE THREAD

**Issue by jhobz** [buntpfotenkatze/KH2Tracker#1]
I haven't tried loading a non-weighted settings seed yet, so maybe this functionality just doesn't work at all, but for sure if you try to load an AP seed into the tracker that was generated with the advanced "weighted settings" page, the tracker crashes.

**Comment by pinkpawkitty** [comment]
@jhobz only now saw the issue, sorry about that (github notifications are now on)

The crash is fixed in: https://github.com/pinkpawkitty/KH2ArchipelagoTracker/releases/tag/1.0-rc2

Unfortunately, weighted settings aren't applied, since I currently only load the settings file.
